
export const MAIN_BATTLE_TANK_HEALTH = 150;
export const MAIN_BATTLE_TANK_DAMAGE = 90;
export const MAIN_BATTLE_TANK_RECEIVED_DAMAGE_REDUCTION = 0.3;
export const ASSAULT_TANK_HEALTH = 100;
export const ASSAULT_TANK_DAMAGE = 140;
